# Generated by Django 2.2.7 on 2020-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('store', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(height_field=200, upload_to='', width_field=200)),
            ],
        ),
    ]
