# Generated by Django 2.2.7 on 2020-02-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200202_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogue',
            field=models.CharField(choices=[('electronics', (('ph', 'phones'), ('tab', 'tablets'), ('acc', 'accessories'))), ('vehicles', (('ca', 'cars'), ('cyc', 'motorcycles'))), ('fashion', (('me', "men's"), ('wo', "women's"))), ('home appliance', (('coo', 'cookers'), ('fa', 'fans')))], max_length=10, null=True),
        ),
    ]
